"""Remove student_number from StudentProfile

Revision ID: 14ed11458ebb
Revises: 85581c612de5
Create Date: 2025-07-14 23:08:01.506341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ed11458ebb'
down_revision = '85581c612de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('student_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_number', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
