"""add teacher_feedback_overrides to essay

Revision ID: 4378eb25ad6c
Revises: bcd7e41410e7
Create Date: 2025-07-15 10:46:24.318886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4378eb25ad6c'
down_revision = 'bcd7e41410e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_feedback_overrides', sa.JSON(), nullable=True, comment='教师对AI评语的覆写（修改/删除）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_column('teacher_feedback_overrides')

    # ### end Alembic commands ###
