"""Initial migration after reset

Revision ID: 6e00a6851fbb
Revises: 
Create Date: 2025-07-13 15:27:34.980928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e00a6851fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sort_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sort_name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False, comment='登录邮箱'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='用户名'),
    sa.Column('phone', sa.String(length=100), nullable=True, comment='手机号'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='哈希密码'),
    sa.Column('role', sa.String(length=20), nullable=False, comment="角色: 'admin', 'teacher', 'student'"),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('entry_year', sa.Integer(), nullable=False),
    sa.Column('graduate_year', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grading_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='创建者ID, null表示系统标准'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_style_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="模板名称, e.g., '小学低年级-鼓励式'"),
    sa.Column('style_instructions', sa.Text(), nullable=False, comment='核心的Prompt风格指令'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='创建者ID, null表示系统预设'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('teacher_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['grading_standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=50), nullable=True, comment='该学生在该班的学号'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='在读状态: active, graduated, withdrawn'),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('essay_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='作业标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='作业描述或要求'),
    sa.Column('teacher_profile_id', sa.Integer(), nullable=False, comment='出题教师ID'),
    sa.Column('grading_standard_id', sa.Integer(), nullable=False, comment='关联的评分标准ID'),
    sa.Column('prompt_style_template_id', sa.Integer(), nullable=True, comment='教师指定的评语风格ID (可选)'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('due_date', sa.DateTime(), nullable=True, comment='截止日期'),
    sa.ForeignKeyConstraint(['grading_standard_id'], ['grading_standards.id'], ),
    sa.ForeignKeyConstraint(['prompt_style_template_id'], ['prompt_style_templates.id'], ),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grading_standard_tags',
    sa.Column('grading_standard_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grading_standard_id'], ['grading_standards.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('grading_standard_id', 'tag_id')
    )
    op.create_table('prompt_style_grade_level_defaults',
    sa.Column('prompt_style_template_id', sa.Integer(), nullable=False),
    sa.Column('grade_level_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Is this template the default for this grade level?'),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_levels.id'], ),
    sa.ForeignKeyConstraint(['prompt_style_template_id'], ['prompt_style_templates.id'], ),
    sa.PrimaryKeyConstraint('prompt_style_template_id', 'grade_level_id')
    )
    op.create_table('teachers_classrooms',
    sa.Column('teacher_profile_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('teacher_profile_id', 'classroom_id')
    )
    op.create_table('teachers_grading_standards',
    sa.Column('teacher_profile_id', sa.Integer(), nullable=False),
    sa.Column('grading_standard_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grading_standard_id'], ['grading_standards.id'], ),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('teacher_profile_id', 'grading_standard_id')
    )
    op.create_table('assignment_classrooms',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['essay_assignments.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('assignment_id', 'classroom_id')
    )
    op.create_table('assignment_student_profiles',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['essay_assignments.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('assignment_id', 'student_profile_id')
    )
    op.create_table('essays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True, comment='关联的作业ID'),
    sa.Column('grading_standard_id', sa.Integer(), nullable=True, comment='自主练习时使用的评分标准ID'),
    sa.Column('content', sa.Text(), nullable=True, comment='作文的文本内容'),
    sa.Column('is_from_ocr', sa.Boolean(), nullable=False, comment='内容是否来自OCR识别'),
    sa.Column('original_image_path', sa.String(length=255), nullable=True, comment='如果来自OCR，原始图片的存储路径'),
    sa.Column('ai_score', sa.JSON(), nullable=True),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('ai_critique', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['essay_assignments.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['grading_standard_id'], ['grading_standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dimension_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimensions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essay_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('manual_score', sa.JSON(), nullable=True),
    sa.Column('manual_comment', sa.Text(), nullable=True),
    sa.Column('annotated_image_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['essay_id'], ['essays.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('essay_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_reviews')
    op.drop_table('rubrics')
    op.drop_table('essays')
    op.drop_table('assignment_student_profiles')
    op.drop_table('assignment_classrooms')
    op.drop_table('teachers_grading_standards')
    op.drop_table('teachers_classrooms')
    op.drop_table('prompt_style_grade_level_defaults')
    op.drop_table('grading_standard_tags')
    op.drop_table('essay_assignments')
    op.drop_table('enrollments')
    op.drop_table('dimensions')
    op.drop_table('teacher_profiles')
    op.drop_table('student_profiles')
    op.drop_table('prompt_style_templates')
    op.drop_table('grading_standards')
    op.drop_table('classrooms')
    op.drop_table('admin_profiles')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('schools')
    op.drop_table('grade_levels')
    # ### end Alembic commands ###
