"""Add PendingSubmission model

Revision ID: 85581c612de5
Revises: a810b22b9c9a
Create Date: 2025-07-14 12:01:59.697782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85581c612de5'
down_revision = 'a810b22b9c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False, comment='关联的作业ID'),
    sa.Column('uploader_id', sa.Integer(), nullable=False, comment='上传者（教师）ID'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='文件存储路径'),
    sa.Column('status', sa.Enum('uploaded', 'preprocessing', 'ocr_processing', 'ocr_completed', 'matching', 'match_completed', 'failed', name='submission_status_enum'), nullable=False, comment='处理状态'),
    sa.Column('ocr_text', sa.Text(), nullable=True, comment='OCR识别出的文本'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='处理失败时的错误信息'),
    sa.Column('matched_student_id', sa.Integer(), nullable=True, comment='AI匹配到的学生ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['essay_assignments.id'], ),
    sa.ForeignKeyConstraint(['matched_student_id'], ['student_profiles.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['teacher_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_submissions')
    # ### end Alembic commands ###
