"""Add AssignmentReport model

Revision ID: 9324af8dd64e
Revises: 9cb622308f9d
Create Date: 2025-08-05 16:22:02.172555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9324af8dd64e'
down_revision = '9cb622308f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('report_data', sa.Text(), nullable=False, comment='AI分析的JSON数据'),
    sa.Column('generated_at', sa.DateTime(), nullable=True, comment='报告生成时间'),
    sa.Column('generated_by', sa.Integer(), nullable=False, comment='报告生成者'),
    sa.ForeignKeyConstraint(['assignment_id'], ['essay_assignments.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_reports')
    # ### end Alembic commands ###
