"""Add annotated_overlay_path to Essay model

Revision ID: 9cb622308f9d
Revises: 4378eb25ad6c
Create Date: 2025-07-18 16:20:47.791489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb622308f9d'
down_revision = '4378eb25ad6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotated_overlay_path', sa.String(length=255), nullable=True, comment='圈画叠加层图片路径'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_column('annotated_overlay_path')

    # ### end Alembic commands ###
