"""Add is_enabled to GradeLevel model

Revision ID: a810b22b9c9a
Revises: c95d9954d660
Create Date: 2025-07-13 16:17:14.813684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a810b22b9c9a'
down_revision = 'c95d9954d660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default='0', comment='是否启用该年级'))

    # ### end Alembic commands ###
    
    # Manually added data migration to enable specific grades by default
    op.execute("UPDATE grade_levels SET is_enabled = 1 WHERE name IN ('二年级', '三年级', '四年级', '五年级')")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_levels', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    # ### end Alembic commands ###
