"""Add teacher_corrected_text and teacher_score to Essay model

Revision ID: bcd7e41410e7
Revises: dccecea44715
Create Date: 2025-07-15 01:01:56.866447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd7e41410e7'
down_revision = 'dccecea44715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_corrected_text', sa.Text(), nullable=True, comment='教师手动校对后的文本'))
        batch_op.add_column(sa.Column('teacher_score', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('final_score', sa.Float(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_essays_status'), ['status'], unique=False)
        batch_op.drop_column('ai_comment')
        batch_op.drop_column('ai_suggestion')
        batch_op.drop_column('ai_critique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_critique', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ai_suggestion', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ai_comment', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_essays_status'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('final_score')
        batch_op.drop_column('teacher_score')
        batch_op.drop_column('teacher_corrected_text')

    # ### end Alembic commands ###
