"""Add original_ocr_text to Essay model

Revision ID: c95d9954d660
Revises: 6e00a6851fbb
Create Date: 2025-07-13 15:54:20.276177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c95d9954d660'
down_revision = '6e00a6851fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_ocr_text', sa.Text(), nullable=True, comment='来自OCR的原始识别文本'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_column('original_ocr_text')

    # ### end Alembic commands ###
