"""Add error_message to Essay model

Revision ID: dccecea44715
Revises: 14ed11458ebb
Create Date: 2025-07-14 23:39:38.332605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccecea44715'
down_revision = '14ed11458ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essays', schema=None) as batch_op:
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###
